In [113]:
import pandas as pd 
import pymysql 
from getpass import getpass
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, mean_absolute_percentage_error

In [6]:
password = getpass("Enter Password: ")
con = pymysql.connect(
    user = "root",
    host = "localhost",
    database = "bike_store_database",
    password = password
)

cursor = con.cursor()

print("Connected Successfully!!!")

Enter Password:  ········

Connected Successfully!!!

In [8]:
data = pd.read_sql(""" SELECT * FROM store_sale""", con)

C:\Users\Data Professor\AppData\Local\Temp\ipykernel_352\3081336644.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(""" SELECT * FROM store_sale""", con)

In [9]:
print(data)

       puchase_date age       age_group gender         country  \
0        11/26/2013  19     Youth (<25)      M          Canada
1        11/26/2015  19     Youth (<25)      M          Canada
2         3/23/2014  49  Adults (35-64)      M       Australia
3         3/23/2016  49  Adults (35-64)      M       Australia
4         5/15/2014  47  Adults (35-64)      F       Australia
...             ...  ..             ...    ...             ...
113031    4/12/2016  41  Adults (35-64)      M  United Kingdom
113032     4/2/2014  18     Youth (<25)      M       Australia
113033     4/2/2016  18     Youth (<25)      M       Australia
113034     3/4/2014  37  Adults (35-64)      F          France
113035     3/4/2016  37  Adults (35-64)      F          France

                   state     category sub_category              product  \
0       British Columbia  Accessories   Bike Racks  Hitch Rack - 4-Bike
1       British Columbia  Accessories   Bike Racks  Hitch Rack - 4-Bike
2        New South Wales  Accessories   Bike Racks  Hitch Rack - 4-Bike
3        New South Wales  Accessories   Bike Racks  Hitch Rack - 4-Bike
4        New South Wales  Accessories   Bike Racks  Hitch Rack - 4-Bike
...                  ...          ...          ...                  ...
113031           England     Clothing        Vests      Classic Vest, S
113032        Queensland     Clothing        Vests      Classic Vest, M
113033        Queensland     Clothing        Vests      Classic Vest, M
113034     Seine (Paris)     Clothing        Vests      Classic Vest, L
113035     Seine (Paris)     Clothing        Vests      Classic Vest, L

       quantity unit_cost unit_price profit  cost revenue
0             8        45        120    590   360   950\r
1             8        45        120    590   360   950\r
2            23        45        120   1366  1035  2401\r
3            20        45        120   1188   900  2088\r
4             4        45        120    238   180   418\r
...         ...       ...        ...    ...   ...     ...
113031        3        24         64    112    72   184\r
113032       22        24         64    655   528  1183\r
113033       22        24         64    655   528  1183\r
113034       24        24         64    684   576  1260\r
113035       23        24         64    655   552  1207\r

[113036 rows x 15 columns]

In [139]:
df = data.copy()

In [140]:
df.columns

Index(['puchase_date', 'age', 'age_group', 'gender', 'country', 'state',
       'category', 'sub_category', 'product', 'quantity', 'unit_cost',
       'unit_price', 'profit', 'cost', 'revenue'],
      dtype='object')

In [141]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   puchase_date  113036 non-null  object
 1   age           113036 non-null  object
 2   age_group     113036 non-null  object
 3   gender        113036 non-null  object
 4   country       113036 non-null  object
 5   state         113036 non-null  object
 6   category      113036 non-null  object
 7   sub_category  113036 non-null  object
 8   product       113036 non-null  object
 9   quantity      113036 non-null  object
 10  unit_cost     113036 non-null  object
 11  unit_price    113036 non-null  object
 12  profit        113036 non-null  object
 13  cost          113036 non-null  object
 14  revenue       113036 non-null  object
dtypes: object(15)
memory usage: 12.9+ MB

In [142]:
df.duplicated().any()

np.True_

In [143]:
df.duplicated().sum()

np.int64(1000)

In [144]:
df.drop_duplicates(inplace = True)

In [145]:
df.isna().any()

puchase_date    False
age             False
age_group       False
gender          False
country         False
state           False
category        False
sub_category    False
product         False
quantity        False
unit_cost       False
unit_price      False
profit          False
cost            False
revenue         False
dtype: bool

In [146]:
df["revenue"] = pd.to_numeric(df["revenue"])
df["cost"] = pd.to_numeric(df["cost"])
df["profit"] = pd.to_numeric(df["profit"])
df["unit_price"] = pd.to_numeric(df["unit_price"])
df["unit_cost"] = pd.to_numeric(df["unit_cost"])
df["quantity"] = pd.to_numeric(df["quantity"])
df["puchase_date"] = pd.to_datetime(df["puchase_date"])

In [147]:
print(df)

       puchase_date age       age_group gender         country  \
0        2013-11-26  19     Youth (<25)      M          Canada
1        2015-11-26  19     Youth (<25)      M          Canada
2        2014-03-23  49  Adults (35-64)      M       Australia
3        2016-03-23  49  Adults (35-64)      M       Australia
4        2014-05-15  47  Adults (35-64)      F       Australia
...             ...  ..             ...    ...             ...
113031   2016-04-12  41  Adults (35-64)      M  United Kingdom
113032   2014-04-02  18     Youth (<25)      M       Australia
113033   2016-04-02  18     Youth (<25)      M       Australia
113034   2014-03-04  37  Adults (35-64)      F          France
113035   2016-03-04  37  Adults (35-64)      F          France

                   state     category sub_category              product  \
0       British Columbia  Accessories   Bike Racks  Hitch Rack - 4-Bike
1       British Columbia  Accessories   Bike Racks  Hitch Rack - 4-Bike
2        New South Wales  Accessories   Bike Racks  Hitch Rack - 4-Bike
3        New South Wales  Accessories   Bike Racks  Hitch Rack - 4-Bike
4        New South Wales  Accessories   Bike Racks  Hitch Rack - 4-Bike
...                  ...          ...          ...                  ...
113031           England     Clothing        Vests      Classic Vest, S
113032        Queensland     Clothing        Vests      Classic Vest, M
113033        Queensland     Clothing        Vests      Classic Vest, M
113034     Seine (Paris)     Clothing        Vests      Classic Vest, L
113035     Seine (Paris)     Clothing        Vests      Classic Vest, L

        quantity  unit_cost  unit_price  profit  cost  revenue
0              8         45         120     590   360      950
1              8         45         120     590   360      950
2             23         45         120    1366  1035     2401
3             20         45         120    1188   900     2088
4              4         45         120     238   180      418
...          ...        ...         ...     ...   ...      ...
113031         3         24          64     112    72      184
113032        22         24          64     655   528     1183
113033        22         24          64     655   528     1183
113034        24         24          64     684   576     1260
113035        23         24          64     655   552     1207

[112036 rows x 15 columns]

In [148]:
x = df.drop(columns=['profit','revenue', 'cost', 'quantity', 'puchase_date', 'age_group'])
y = df['revenue']

In [149]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25, random_state = 35)

In [150]:
x_train.shape, y_train.shape

((84027, 9), (84027,))

In [151]:
def generate_transformer(predictors):
    predictors = predictors.copy()

    num_cols = predictors.select_dtypes(include=['number']).columns
    cat_cols = predictors.select_dtypes(include=['object']).columns

    num_pipe = Pipeline([
        ("imputer", SimpleImputer(strategy = 'median')),
        ("scaler", StandardScaler())
    ])

    cat_pipe = Pipeline([
        ("imputer", SimpleImputer(strategy = "most_frequent")),
        ("encoder", OrdinalEncoder(handle_unknown = "use_encoded_value", unknown_value = -1))
    ])


    transformer = ColumnTransformer(
        transformers=[
            ("num_pipe", num_pipe, num_cols),
            ("cat_pipe", cat_pipe, cat_cols)
        ],
        remainder = "drop"
    )

    return transformer

processor = generate_transformer(x)

In [152]:
processor

ColumnTransformer(transformers=[('num_pipe',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 Index(['unit_cost', 'unit_price'], dtype='object')),
                                ('cat_pipe',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1))]),
                                 Index(['age', 'gender', 'country', 'state', 'category', 'sub_category',
       'product'],
      dtype='object'))])

In [153]:
def predict_regressor(transformer, model, model_name):

    pipeline = Pipeline([
        ("processor", transformer),
        ("regressor", model)
    ])

    pipeline.fit(x_train, y_train)

    prediction = pipeline.predict(x_test)

    r2 = r2_score(y_test, prediction)
    mae = mean_absolute_error(y_test, prediction)
    mape = mean_absolute_percentage_error(y_test, prediction)

    
    evaluation_table = pd.DataFrame({
        "model_name": [model_name],
        "r2_score": [r2],
        "MAE": [mae],
        "MAPE": [mape]
    })

    return evaluation_table

In [154]:
predict_regressor(processor, LinearRegression(), "Linear Regression")

          model_name  r2_score         MAE      MAPE
0  Linear Regression  0.697787  399.641838  3.239633

In [155]:
predict_regressor(processor, RandomForestRegressor(), "Random Forest")

      model_name  r2_score         MAE      MAPE
0  Random Forest  0.700919  303.293141  1.114024

In [156]:
predict_regressor(processor, DecisionTreeRegressor(), "Decision Tree")

      model_name  r2_score         MAE      MAPE
0  Decision Tree  0.669835  304.678595  1.083227

In [157]:
predict_regressor(processor, XGBRegressor(), "XGB")

  model_name  r2_score         MAE      MAPE
0        XGB  0.718215  313.644318  1.221402

In [159]:
rf_model = Pipeline([
    ("processor", processor),
    ("rf_model", RandomForestRegressor())
]
)
rf_model.fit(x_train, y_train)

Pipeline(steps=[('processor',
                 ColumnTransformer(transformers=[('num_pipe',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['unit_cost', 'unit_price'], dtype='object')),
                                                 ('cat_pipe',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                                  unknown_value=-1))]),
                                                  Index(['age', 'gender', 'country', 'state', 'category', 'sub_category',
       'product'],
      dtype='object'))])),
                ('rf_model', RandomForestRegressor())])

In [160]:
rf_importance = rf_model.named_steps["rf_model"].feature_importances_

In [161]:
rf_importance

array([0.34316209, 0.48592762, 0.05025947, 0.0085195 , 0.01034194,
       0.03028066, 0.02562707, 0.02206375, 0.0238179 ])

In [162]:
x.columns

Index(['age', 'gender', 'country', 'state', 'category', 'sub_category',
       'product', 'unit_cost', 'unit_price'],
      dtype='object')

In [163]:
importance_df = pd.DataFrame(
    {
        "Features":  x_train.columns,
        "Importance": rf_importance
    }
)

print(importance_df.sort_values(by="Importance",  ascending = False))

       Features  Importance
1        gender    0.485928
0           age    0.343162
2       country    0.050259
5  sub_category    0.030281
6       product    0.025627
8    unit_price    0.023818
7     unit_cost    0.022064
4      category    0.010342
3         state    0.008520

In [168]:
x_df = df.drop(columns=['profit','revenue', 'cost', 'quantity', 'puchase_date', 'age_group'])
y_new = df['revenue']

In [170]:
x_df['price_to_category_avg'] = x_df['unit_price'] / x_df.groupby('category')['unit_price'].transform('mean')
x_df['avg_revenue_country'] = df.groupby('country')['revenue'].transform('mean')
x_df['avg_revenue_product'] = df.groupby('product')['revenue'].transform('mean')
x_df['price_squared'] = df['unit_price'] ** 2
x_df['month'] = pd.to_datetime(df['puchase_date']).dt.month
x_df['day_of_week'] = pd.to_datetime(df['puchase_date']).dt.dayofweek
x_df['price_to_product_avg'] = df['unit_price'] / x_df.groupby('product')['unit_price'].transform('mean')
x_df['price_rank_in_category'] = df.groupby('category')['unit_price'].rank(pct=True)
x_df['product_freq'] = df['product'].map(df['product'].value_counts())
x_df['product_revenue_mean'] = df.groupby('product')['revenue'].transform('mean')

In [171]:
x_train, x_test, y_train, y_test = train_test_split(x_df,y_new, test_size = 0.25, random_state = 35)

In [172]:
x_train.columns

Index(['age', 'gender', 'country', 'state', 'category', 'sub_category',
       'product', 'unit_cost', 'unit_price', 'price_to_category_avg',
       'avg_revenue_country', 'avg_revenue_product', 'price_squared', 'month',
       'day_of_week', 'price_to_product_avg', 'price_rank_in_category',
       'product_freq', 'product_revenue_mean'],
      dtype='object')

In [173]:
print(x_train.head())

      age gender         country             state     category  \
86347  42      M   United States        California  Accessories
58619  43      M  United Kingdom           England        Bikes
49809  25      M       Australia   New South Wales        Bikes
82179  26      M          Canada  British Columbia  Accessories
95194  21      M   United States        California  Accessories

          sub_category                 product  unit_cost  unit_price  \
86347  Tires and Tubes     Patch Kit/8 Patches          1           2
58619       Road Bikes   Road-550-W Yellow, 48        713        1120
49809   Mountain Bikes  Mountain-200 Black, 38       1252        2295
82179  Tires and Tubes      Mountain Tire Tube          2           5
95194  Tires and Tubes      Mountain Tire Tube          2           5

       price_to_category_avg  avg_revenue_country  avg_revenue_product  \
86347               0.117703           715.167302            27.272621
58619               0.588946           784.193089          1486.796117
49809               1.206814           893.006193          2790.242702
82179               0.294258           563.640265            68.975628
95194               0.294258           715.167302            68.975628

       price_squared  month  day_of_week  price_to_product_avg  \
86347              4     12            4                   1.0
58619        1254400      6            2                   1.0
49809        5267025      1            0                   1.0
82179             25     12            5                   1.0
95194             25     11            3                   1.0

       price_rank_in_category  product_freq  product_revenue_mean
86347                0.073992         10256             27.272621
58619                0.309219           412           1486.796117
49809                0.500834          1199           2790.242702
82179                0.358423          6688             68.975628
95194                0.358423          6688             68.975628

In [179]:
def generate_transformer(predictors):
    predictors = predictors.copy()

    num_cols = predictors.select_dtypes(include=['number']).columns
    cat_cols = predictors.select_dtypes(include=['object']).columns

    num_pipe = Pipeline([
        ("imputer", SimpleImputer(strategy = 'median')),
        ("scaler", StandardScaler())
    ])

    cat_pipe = Pipeline([
        ("imputer", SimpleImputer(strategy = "most_frequent")),
        ("encoder", OrdinalEncoder(handle_unknown = "use_encoded_value", unknown_value = -1))
    ])


    transformer = ColumnTransformer(
        transformers=[
            ("num_pipe", num_pipe, num_cols),
            ("cat_pipe", cat_pipe, cat_cols)
        ],
        remainder = "drop"
    )

    return transformer

processor_new = generate_transformer(x_df)

In [180]:
def predict_regressor(transformer, model, model_name):

    pipeline = Pipeline([
        ("processor", transformer),
        ("regressor", model)
    ])

    pipeline.fit(x_train, y_train)

    prediction = pipeline.predict(x_test)

    r2 = r2_score(y_test, prediction)
    mae = mean_absolute_error(y_test, prediction)
    mape = mean_absolute_percentage_error(y_test, prediction)

    
    evaluation_table = pd.DataFrame({
        "model_name": [model_name],
        "r2_score": [r2],
        "MAE": [mae],
        "MAPE": [mape]
    })

    return evaluation_table

In [181]:
predict_regressor(processor_new, LinearRegression(), "Linear Regression")

          model_name  r2_score         MAE      MAPE
0  Linear Regression  0.715366  346.471939  1.761182

In [182]:
predict_regressor(processor_new, RandomForestRegressor(), "Random Forest")

      model_name  r2_score         MAE      MAPE
0  Random Forest  0.695113  314.622856  1.161328

In [183]:
predict_regressor(processor_new, DecisionTreeRegressor(), "Decision Tree")

      model_name  r2_score         MAE      MAPE
0  Decision Tree   0.46527  351.767787  1.181549

In [184]:
predict_regressor(processor_new, XGBRegressor(), "XGB")

  model_name  r2_score         MAE     MAPE
0        XGB  0.710858  313.205292  1.22677